version: "3.8"
services:
 mongodb:
    image: mongo:7.0.8
    restart: always
    ports:
      - "8092:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoose254
      MONGO_INITDB_ROOT_PASSWORD: Mongoosepass